version: '3.8'
services:
  db:
    image: mysql:8.0
    container_name: froome-db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: froome
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: [ "CMD-SHELL", "mysqladmin ping -h localhost -u root --password=password" ]
      interval: 10s
      timeout: 5s
      retries: 5

  user:
    depends_on:
      db:
        condition: service_healthy

    build:
      context: .
      dockerfile: user-service/Dockerfile
    environment:
      DB_URL: jdbc:mysql://froome-db:3306/froome
      PORT: 8180
    ports:
      - "8180:8180"

  product:
    depends_on:
      db:
        condition: service_healthy
    build:
      context: .
      dockerfile: product-service/Dockerfile
    environment:
      DB_URL: jdbc:mysql://froome-db:3306/froome
      PORT: 8181
    ports:
      - "8181:8181"

  payment:
    depends_on:
      db:
        condition: service_healthy
    build:
      context: .
      dockerfile: payment-service/Dockerfile
    environment:
      DB_URL: jdbc:mysql://froome-db:3306/froome
      PORT: 8182
    ports:
      - "8182:8182"

  order:
    depends_on:
      db:
        condition: service_healthy
    build:
      context: .
      dockerfile: order-service/Dockerfile
    environment:
      DB_URL: jdbc:mysql://froome-db:3306/froome
      PORT: 8183
    ports:
      - "8183:8183"

  vue-app:
    build:
      context: ./froome-ui
      dockerfile: Dockerfile
    environment:
      - user_api_url=user:8180
      - product_api_url=product:8181
      - payment_api_url=payment:8182
      - order_api_url=order:8183
    depends_on:
      - user
      - product
      - payment
      - order
    ports:
      - "80:80"


volumes:
  db_data:
