server:
  port: ${PORT:8985}

spring:
  cloud:
    config:
      server:
        git:
          uri: ${GIT_URI:https://github.com/robjo82/froome.git}
          search-paths: 'config-service'
          default-label: main

logging:
  level:
    org.springframework.cloud.config.client: INFO
    org.springframework.cloud.context.scope.GenericScope: INFO
    org.springframework.boot.context.config: INFO
